$(document).ready(function () {


    $("html").on("click", function () {
        $(".crowd")[0].play();
    })


    $(".m1").on("mousedown", function () {
        $("html").css("background-color", "black")
        $(".title").css("fill", "red")
        $(".hover1").css("display", "block")
        $(".m1").css("display", "none")
        $(".crowd")[0].pause();
        $(".stone")[0].play();
        $(".balloon1").css("display", "none")
        $(".balloon2").css("display", "none")
        $(".balloon3").css("display", "none")
        $(".balloon4").css("display", "none")
        $(".balloon5").css("display", "none")
        $(".balloon6").css("display", "none")
        $(".balloon7").css("display", "none")
        $(".balloon8").css("display", "none")
        $(".balloon9").css("display", "none")
        $(".balloon10").css("display", "none")
        $(".balloon11").css("display", "none")

    })
    $(".hover1").on("mouseup", function () {
        $("html").css("background-color", "white")
        $(".title").css("fill", "black")
        $(".m1").css("display", "block")
        $(".hover1").css("display", "none")
        $(".stone")[0].pause();
        $(".balloon1").css("display", "block")
        $(".balloon2").css("display", "block")
        $(".balloon3").css("display", "block")
        $(".balloon4").css("display", "block")
        $(".balloon5").css("display", "block")
        $(".balloon6").css("display", "block")
        $(".balloon7").css("display", "block")
        $(".balloon8").css("display", "block")
        $(".balloon9").css("display", "block")
        $(".balloon10").css("display", "block")
        $(".balloon11").css("display", "block")
    })
    $(".w1").on("mousedown", function () {
        $("html").css("background-color", "black")
        $(".title").css("fill", "red")
        $(".hover2").css("display", "block")
        $(".w1").css("display", "none")
        $(".crowd")[0].pause();
        $(".stone")[0].play();
        $(".balloon1").css("display", "none")
        $(".balloon2").css("display", "none")
        $(".balloon3").css("display", "none")
        $(".balloon4").css("display", "none")
        $(".balloon5").css("display", "none")
        $(".balloon6").css("display", "none")
        $(".balloon7").css("display", "none")
        $(".balloon8").css("display", "none")
        $(".balloon9").css("display", "none")
        $(".balloon10").css("display", "none")
        $(".balloon11").css("display", "none")

    })
    $(".hover2").on("mouseup", function () {
        $("html").css("background-color", "white")
        $(".title").css("fill", "black")
        $(".w1").css("display", "block")
        $(".hover2").css("display", "none")
        $(".stone")[0].pause();
        $(".balloon1").css("display", "block")
        $(".balloon2").css("display", "block")
        $(".balloon3").css("display", "block")
        $(".balloon4").css("display", "block")
        $(".balloon5").css("display", "block")
        $(".balloon6").css("display", "block")
        $(".balloon7").css("display", "block")
        $(".balloon8").css("display", "block")
        $(".balloon9").css("display", "block")
        $(".balloon10").css("display", "block")
        $(".balloon11").css("display", "block")
    })

    $(".m2").on("mousedown", function () {
        $("html").css("background-color", "black")
        $(".title").css("fill", "red")
        $(".hover3").css("display", "block")
        $(".m2").css("display", "none")
        $(".crowd")[0].pause();
        $(".stone")[0].play();
        $(".balloon1").css("display", "none")
        $(".balloon2").css("display", "none")
        $(".balloon3").css("display", "none")
        $(".balloon4").css("display", "none")
        $(".balloon5").css("display", "none")
        $(".balloon6").css("display", "none")
        $(".balloon7").css("display", "none")
        $(".balloon8").css("display", "none")
        $(".balloon9").css("display", "none")
        $(".balloon10").css("display", "none")
        $(".balloon11").css("display", "none")

    })
    $(".hover3").on("mouseup", function () {
        $("html").css("background-color", "white")
        $(".title").css("fill", "black")
        $(".m2").css("display", "block")
        $(".hover3").css("display", "none")
        $(".stone")[0].pause();
        $(".balloon1").css("display", "block")
        $(".balloon2").css("display", "block")
        $(".balloon3").css("display", "block")
        $(".balloon4").css("display", "block")
        $(".balloon5").css("display", "block")
        $(".balloon6").css("display", "block")
        $(".balloon7").css("display", "block")
        $(".balloon8").css("display", "block")
        $(".balloon9").css("display", "block")
        $(".balloon10").css("display", "block")
        $(".balloon11").css("display", "block")
    })

    $(".w2").on("mousedown", function () {
        $("html").css("background-color", "black")
        $(".title").css("fill", "red")
        $(".hover4").css("display", "block")
        $(".w2").css("display", "none")
        $(".crowd")[0].pause();
        $(".stone")[0].play();
        $(".balloon1").css("display", "none")
        $(".balloon2").css("display", "none")
        $(".balloon3").css("display", "none")
        $(".balloon4").css("display", "none")
        $(".balloon5").css("display", "none")
        $(".balloon6").css("display", "none")
        $(".balloon7").css("display", "none")
        $(".balloon8").css("display", "none")
        $(".balloon9").css("display", "none")
        $(".balloon10").css("display", "none")
        $(".balloon11").css("display", "none")

    })
    $(".hover4").on("mouseup", function () {
        $("html").css("background-color", "white")
        $(".title").css("fill", "black")
        $(".w2").css("display", "block")
        $(".hover4").css("display", "none")
        $(".stone")[0].pause();
        $(".balloon1").css("display", "block")
        $(".balloon2").css("display", "block")
        $(".balloon3").css("display", "block")
        $(".balloon4").css("display", "block")
        $(".balloon5").css("display", "block")
        $(".balloon6").css("display", "block")
        $(".balloon7").css("display", "block")
        $(".balloon8").css("display", "block")
        $(".balloon9").css("display", "block")
        $(".balloon10").css("display", "block")
        $(".balloon11").css("display", "block")
    })

    $(".w3").on("mousedown", function () {
        $("html").css("background-color", "black")
        $(".title").css("fill", "red")
        $(".hover5").css("display", "block")
        $(".w3").css("display", "none")
        $(".crowd")[0].pause();
        $(".stone")[0].play();
        $(".balloon1").css("display", "none")
        $(".balloon2").css("display", "none")
        $(".balloon3").css("display", "none")
        $(".balloon4").css("display", "none")
        $(".balloon5").css("display", "none")
        $(".balloon6").css("display", "none")
        $(".balloon7").css("display", "none")
        $(".balloon8").css("display", "none")
        $(".balloon9").css("display", "none")
        $(".balloon10").css("display", "none")
        $(".balloon11").css("display", "none")

    })
    $(".hover5").on("mouseup", function () {
        $("html").css("background-color", "white")
        $(".title").css("fill", "black")
        $(".w3").css("display", "block")
        $(".hover5").css("display", "none")
        $(".stone")[0].pause();
        $(".balloon1").css("display", "block")
        $(".balloon2").css("display", "block")
        $(".balloon3").css("display", "block")
        $(".balloon4").css("display", "block")
        $(".balloon5").css("display", "block")
        $(".balloon6").css("display", "block")
        $(".balloon7").css("display", "block")
        $(".balloon8").css("display", "block")
        $(".balloon9").css("display", "block")
        $(".balloon10").css("display", "block")
        $(".balloon11").css("display", "block")
    })

    $(".m3").on("mousedown", function () {
        $("html").css("background-color", "black")
        $(".title").css("fill", "red")
        $(".hover6").css("display", "block")
        $(".m3").css("display", "none")
        $(".crowd")[0].pause();
        $(".stone")[0].play();
        $(".balloon1").css("display", "none")
        $(".balloon2").css("display", "none")
        $(".balloon3").css("display", "none")
        $(".balloon4").css("display", "none")
        $(".balloon5").css("display", "none")
        $(".balloon6").css("display", "none")
        $(".balloon7").css("display", "none")
        $(".balloon8").css("display", "none")
        $(".balloon9").css("display", "none")
        $(".balloon10").css("display", "none")
        $(".balloon11").css("display", "none")

    })
    $(".hover6").on("mouseup", function () {
        $("html").css("background-color", "white")
        $(".title").css("fill", "black")
        $(".m3").css("display", "block")
        $(".hover6").css("display", "none")
        $(".stone")[0].pause();
        $(".balloon1").css("display", "block")
        $(".balloon2").css("display", "block")
        $(".balloon3").css("display", "block")
        $(".balloon4").css("display", "block")
        $(".balloon5").css("display", "block")
        $(".balloon6").css("display", "block")
        $(".balloon7").css("display", "block")
        $(".balloon8").css("display", "block")
        $(".balloon9").css("display", "block")
        $(".balloon10").css("display", "block")
        $(".balloon11").css("display", "block")
    })

    $(".m4").on("mousedown", function () {
        $("html").css("background-color", "black")
        $(".title").css("fill", "red")
        $(".hover7").css("display", "block")
        $(".m4").css("display", "none")
        $(".crowd")[0].pause();
        $(".stone")[0].play();
        $(".balloon1").css("display", "none")
        $(".balloon2").css("display", "none")
        $(".balloon3").css("display", "none")
        $(".balloon4").css("display", "none")
        $(".balloon5").css("display", "none")
        $(".balloon6").css("display", "none")
        $(".balloon7").css("display", "none")
        $(".balloon8").css("display", "none")
        $(".balloon9").css("display", "none")
        $(".balloon10").css("display", "none")
        $(".balloon11").css("display", "none")

    })
    $(".hover7").on("mouseup", function () {
        $("html").css("background-color", "white")
        $(".title").css("fill", "black")
        $(".m4").css("display", "block")
        $(".hover7").css("display", "none")
        $(".stone")[0].pause();
        $(".balloon1").css("display", "block")
        $(".balloon2").css("display", "block")
        $(".balloon3").css("display", "block")
        $(".balloon4").css("display", "block")
        $(".balloon5").css("display", "block")
        $(".balloon6").css("display", "block")
        $(".balloon7").css("display", "block")
        $(".balloon8").css("display", "block")
        $(".balloon9").css("display", "block")
        $(".balloon10").css("display", "block")
        $(".balloon11").css("display", "block")
    })

    $(".w4").on("mousedown", function () {
        $("html").css("background-color", "black")
        $(".title").css("fill", "red")
        $(".hover8").css("display", "block")
        $(".w4").css("display", "none")
        $(".crowd")[0].pause();
        $(".stone")[0].play();
        $(".balloon1").css("display", "none")
        $(".balloon2").css("display", "none")
        $(".balloon3").css("display", "none")
        $(".balloon4").css("display", "none")
        $(".balloon5").css("display", "none")
        $(".balloon6").css("display", "none")
        $(".balloon7").css("display", "none")
        $(".balloon8").css("display", "none")
        $(".balloon9").css("display", "none")
        $(".balloon10").css("display", "none")
        $(".balloon11").css("display", "none")

    })
    $(".hover8").on("mouseup", function () {
        $("html").css("background-color", "white")
        $(".title").css("fill", "black")
        $(".w4").css("display", "block")
        $(".hover8").css("display", "none")
        $(".stone")[0].pause();
        $(".balloon1").css("display", "block")
        $(".balloon2").css("display", "block")
        $(".balloon3").css("display", "block")
        $(".balloon4").css("display", "block")
        $(".balloon5").css("display", "block")
        $(".balloon6").css("display", "block")
        $(".balloon7").css("display", "block")
        $(".balloon8").css("display", "block")
        $(".balloon9").css("display", "block")
        $(".balloon10").css("display", "block")
        $(".balloon11").css("display", "block")
    })

    $(".w5").on("mousedown", function () {
        $("html").css("background-color", "black")
        $(".title").css("fill", "red")
        $(".hover9").css("display", "block")
        $(".w5").css("display", "none")
        $(".crowd")[0].pause();
        $(".stone")[0].play();
        $(".balloon9").css("display", "none")
        $(".balloon1").css("display", "none")
        $(".balloon2").css("display", "none")
        $(".balloon3").css("display", "none")
        $(".balloon4").css("display", "none")
        $(".balloon5").css("display", "none")
        $(".balloon6").css("display", "none")
        $(".balloon7").css("display", "none")
        $(".balloon8").css("display", "none")
        $(".balloon9").css("display", "none")
        $(".balloon10").css("display", "none")
        $(".balloon11").css("display", "none")

    })
    $(".hover9").on("mouseup", function () {
        $("html").css("background-color", "white")
        $(".title").css("fill", "black")
        $(".w5").css("display", "block")
        $(".hover9").css("display", "none")
        $(".stone")[0].pause();
        $(".balloon9").css("display", "block")
        $(".balloon1").css("display", "block")
        $(".balloon2").css("display", "block")
        $(".balloon3").css("display", "block")
        $(".balloon4").css("display", "block")
        $(".balloon5").css("display", "block")
        $(".balloon6").css("display", "block")
        $(".balloon7").css("display", "block")
        $(".balloon8").css("display", "block")
        $(".balloon9").css("display", "block")
        $(".balloon10").css("display", "block")
        $(".balloon11").css("display", "block")
    })

    $(".m5").on("mousedown", function () {
        $("html").css("background-color", "black")
        $(".title").css("fill", "red")
        $(".hover10").css("display", "block")
        $(".m5").css("display", "none")
        $(".crowd")[0].pause();
        $(".stone")[0].play();
        $(".balloon10").css("display", "none")
        $(".balloon1").css("display", "none")
        $(".balloon2").css("display", "none")
        $(".balloon3").css("display", "none")
        $(".balloon4").css("display", "none")
        $(".balloon5").css("display", "none")
        $(".balloon6").css("display", "none")
        $(".balloon7").css("display", "none")
        $(".balloon8").css("display", "none")
        $(".balloon9").css("display", "none")
        $(".balloon10").css("display", "none")
        $(".balloon11").css("display", "none")

    })
    $(".hover10").on("mouseup", function () {
        $("html").css("background-color", "white")
        $(".title").css("fill", "black")
        $(".m5").css("display", "block")
        $(".hover10").css("display", "none")
        $(".stone")[0].pause();
        $(".balloon10").css("display", "block")
        $(".balloon1").css("display", "block")
        $(".balloon2").css("display", "block")
        $(".balloon3").css("display", "block")
        $(".balloon4").css("display", "block")
        $(".balloon5").css("display", "block")
        $(".balloon6").css("display", "block")
        $(".balloon7").css("display", "block")
        $(".balloon8").css("display", "block")
        $(".balloon9").css("display", "block")
        $(".balloon10").css("display", "block")
        $(".balloon11").css("display", "block")
    })

    $(".m6").on("mousedown", function () {
        $("html").css("background-color", "black")
        $(".title").css("fill", "red")
        $(".hover11").css("display", "block")
        $(".m6").css("display", "none")
        $(".crowd")[0].pause();
        $(".stone")[0].play();
        $(".balloon1").css("display", "none")
        $(".balloon2").css("display", "none")
        $(".balloon3").css("display", "none")
        $(".balloon4").css("display", "none")
        $(".balloon5").css("display", "none")
        $(".balloon6").css("display", "none")
        $(".balloon7").css("display", "none")
        $(".balloon8").css("display", "none")
        $(".balloon9").css("display", "none")
        $(".balloon10").css("display", "none")
        $(".balloon11").css("display", "none")

    })
    $(".hover11").on("mouseup", function () {
        $("html").css("background-color", "white")
        $(".title").css("fill", "black")
        $(".m6").css("display", "block")
        $(".hover11").css("display", "none")
        $(".stone")[0].pause();
        $(".balloon1").css("display", "block")
        $(".balloon2").css("display", "block")
        $(".balloon3").css("display", "block")
        $(".balloon4").css("display", "block")
        $(".balloon5").css("display", "block")
        $(".balloon6").css("display", "block")
        $(".balloon7").css("display", "block")
        $(".balloon8").css("display", "block")
        $(".balloon9").css("display", "block")
        $(".balloon10").css("display", "block")
        $(".balloon11").css("display", "block")
    })
})